# Generated by Django 4.1.1 on 2022-09-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="desciption",
            new_name="description",
        ),
    ]
